---

x-common: &common
  build:
    target: development
    context: .
    dockerfile: Dockerfile-dev
    args:
      - PYTHON_VERSION=${PYTHON_VERSION:-3.11}
  image: "picodi-fastapi-example:dev"
  volumes:
    - .:/opt/code

services:
  devtools:
    <<: *common
    command: sleep infinity

  app:
    <<: *common
    restart: "no"
    ports:
      - "8000:8000"

  redis:
    image: "redis:7.2.5-alpine"
    restart: "no"
    ports:
      - "6379:6379"
